/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.4/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.3-jre")
    implementation("de.learnlib.distribution:learnlib-distribution:0.17.0")
    implementation("net.automatalib.distribution:automata-distribution:0.11.0")
    
    implementation("ch.qos.logback:logback-core:1.5.12") 
    implementation("ch.qos.logback:logback-classic:1.5.12") 

}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.9.1")
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("uelearner.App")
}


tasks.register<Copy>("copyLibs") {
    from(configurations.runtimeClasspath)
    into("$buildDir/externalLibs")  // You can change this path if you want it elsewhere
}

tasks.named("build") {
    dependsOn("copyLibs")
}
